### ISSUE TITLE
Security of MX config retrieval method

### ISSUE THREAD

**Issue by mimi89999** [benbucksch/autoconfig-spec#13]
Hello,

I have some doubts about the security of the the MX config retrieval method: https://benbucksch.github.io/autoconfig-spec/draft-ietf-mailmaint-autoconfig.html#name-mx

The spec describes the following step:
> Remove the first component from the MX hostname, i.e. everything up to and including the first ., and use that as value for %MXFULLDOMAIN%.

While it's common, to use subdomains like `mx0` in MX records, I don't think that it's prohibited to use domains under a public suffix. In fact https://datatracker.ietf.org/doc/html/rfc1912#section-2.5 states that:
> It is a good idea to give every host an MX record, even if it points to itself!

Therefore the domain `example.com` could have the following record (omitting some fields for clarity):
```
example.com.    MX    10    example.com.pl.
```
The domain `example.com.pl` could also have an MX record pointing to itself:
```
example.com.pl.    MX    10    example.com.pl.
```

Following the first step and removing the first component will yield `%MXFULLDOMAIN%` equal to `com.pl`. Then in step 3.1 `https://autoconfig.%MXFULLDOMAIN%/.well-known/mail-v1.xml?emailaddress=%EMAILADDRESS%` will be requested, that is `https://autoconfig.com.pl/.well-known/mail-v1.xml`. However, `autoconfig.com.pl` is a domain available for registration.

**Comment by benbucksch** [comment]
The [spec](https://benbucksch.github.io/autoconfig-spec/draft-ietf-mailmaint-autoconfig.html#name-mx) states:
"
From that MX hostname, 2 values are extracted:
* Remove the first component from the MX hostname, i.e. everything up to and including the first ., and use that as value for %MXFULLDOMAIN%.
* Extract only the second-level domain from the MX hostname, and use that as value for %MXBASEDOMAIN%. To determine the second-level domain, use the [Public Suffic List](https://publicsuffix.org/) or a similarly suited method, to correctly handle domains like ".co.uk" and ".com.au".
"

1. The `%MXBASEDOMAIN%` already explicitly refers to the public suffix list and ".com.au"
2. In your example, the `%MXFULLDOMAIN%` would be shorter than `%MXBASEDOMAIN%`. As the name implies, that was not intended. We could define that `%MXFULLDOMAIN%` should be skipped, if it's shorter than or identical (length) to `%MXBASEDOMAIN%`. That should fix the issue you present here.

3. This is an extreme edge case. For important domains, such flimsy domains should not be used. It is the responsibility of the domain owner to ensure that his domain is secure. If "com.pl" is not an official domain for public registration, but only a small company reselling domains, then "example.com.pl" put itself in an unstable domain. As such, the extend of the problem is very limited to such third level domains.

**Comment by mimi89999** [comment]
> This is an extreme edge case. For important domains, such flimsy domains should not be used. It is the responsibility of the domain owner to ensure that his domain is secure. If "com.pl" is not an official domain for public registration, but only a small company reselling domains, then "example.com.pl" put itself in an unstable domain. As such, the extend of the problem is very limited to such third level domains.

The `com.pl` domain is managed by the `.pl` registry. It's one of the functional domains: https://dns.pl/lista_domen_funkcjonalnych. They also have some regional domains: https://dns.pl/lista_domen_regionalnych

In fact, this will also work for `example.co.uk` with ` autoconfig.co.uk` available for registration and some top level domains like `example.pl` (`autoconfig.pl`), `example.moe` (`autoconfig.moe`), etc. Namecheap shows quite an impressive list: https://www.namecheap.com/domains/registration/results/?type=beast&share=150e9d107aa011efb5bd8b16e8d18951&sort=Default

> In your example, the %MXFULLDOMAIN% would be shorter than %MXBASEDOMAIN%. As the name implies, that was not intended. We could define that %MXFULLDOMAIN% should be skipped, if it's shorter than or identical (length) to %MXBASEDOMAIN%. That should fix the issue you present here. Would you concur that this solves the issue?

I think that this will mostly solve the issue. While the name might suggest that, I believe that it's better to explicitly state that in the spec. There are some rare cases of domains like `netlib.re` with subdomains available for registration that are not present in the [PLS](https://publicsuffix.org/list/public_suffix_list.dat), but those are flimsy domains that you talked about in 3.

**Comment by benbucksch** [comment]
> I think that this will mostly solve the issue. While the name might suggest that, I believe that it's better to explicitly state that in the spec

OK, fixed in d53b5beeb. Thanks for pointing this out.

**Comment by benbucksch** [comment]
I've simplified this to: "... `%MXFULLDOMAIN%`. Use it only if it is longer than `%MXBASEDOMAIN%`."

**Comment by mimi89999** [comment]
> If it is shorter or the same length as `%MXBASEDOMAIN%`, then skip it.

Maybe changing the wording to include `MUST` would be better? Also 3.1 and 3.2 would be the same in that case.

**Comment by benbucksch** [comment]
> Maybe changing the wording to include MUST would be better?

As mentioned, I've changed it so "Use it only if it is longer than `%MXBASEDOMAIN%`."

> Also 3.1 should be skipped.

Yes, that's what the sentence above means. 3.1 is `https://autoconfig.%MXFULLDOMAIN%/.well-known/mail-v1.xml?emailaddress=%EMAILADDRESS%` , so if you're not using `%MXFULLDOMAIN%`, that means you're skipping this step 3.1.

**Comment by mimi89999** [comment]
Hm. That makes sense, but I still have some doubts. This is not an obvious issue and I fear that some implementations might make an issue here.
